workflows:
  android-release:
    name: Vyapar Billing APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fix folder structure
        script: |
          mkdir -p lib
          mv main.dart lib/main.dart || true
          mv *_screen.dart lib/ || true
          mv *_provider.dart lib/ || true
          mv *.dart lib/ || true
          ls -la
          ls -la lib/
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
